### ISSUE TITLE
Please verify that both the operating system and the processor support Intel(R) MOVBE, F16C, FMA, BMI, LZCNT and AVX2 instructions.

### ISSUE THREAD

**Issue by MikeChenfu** [01org/yask#11]
Hello,

I got an error " Please verify that both the operating system and the processor support Intel(R) MOVBE, F16C, FMA, BMI, LZCNT and AVX2 instructions." when I run YASK.

Following is the command:
mpirun-n 2 -ppn2 ./stencil-run.sh -arch hsw--\-nr 1 -nrx 2 -d 1024 -dx 512 -b 64 -bz 96

CPU : Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
MIC  : Intel Xeon Phi coprocessors 5110P

Thanks for your help.

**Comment by chuckyount** [comment]
The Intel(R) Xeon(R) CPU E5-2670 does not support AVX2. Please try compiling with 'arch=snb' and running with '-arch snb'.

**Comment by MikeChenfu** [comment]
It works. Thank you very much.

**Comment by chuckyount** [comment]
You're welcome.
