### ISSUE TITLE
MPI now needed

### ISSUE THREAD

**Issue by dkokron** [01org/yask#3]
Seems mpi=1 is required even for single node builds.

icpc -V
Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 17.0.0.098 Build 20160721

make arch=hsw stencil=iso3dfd
Header files generated.
icpc -g -O3 -std=c++11 -Wall -xCORE-AVX2 -debug extended -Fa -restrict -ansi-alias -fno-alias -fimf-precision=low -fast-transcendentals -no-prec-sqrt -no-prec-div -fp-model fast=2 -fno-protect-parens -rcd -ftz -fma -fimf-domain-exclusion=none -qopt-assume-safe-padding -qopt-report=5 -qopt-report-phase=VEC,PAR,OPENMP,IPO,LOOP -no-diag-message-catalog -DMAX_EXCH_DIST=1 -DUSE_INTRIN256 -DREAL_BYTES=4 -DLAYOUT_3D=Layout_123 -DLAYOUT_4D=Layout_2314 -DTIME_DIM_SIZE=2 -DDEF_RANK_SIZE=1024 -DDEF_BLOCK_SIZE=64 -DDEF_BLOCK_THREADS=2 -DDEF_THREAD_FACTOR=1 -DDEF_PAD=1 -DARCH_HSW -DNO_STORE_INTRINSICS -DUSE_STREAMING_STORE  -fopenmp   -c -o src/stencil_main.hsw.o src/stencil_main.cpp
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
icpc -g -O3 -std=c++11 -Wall -xCORE-AVX2 -debug extended -Fa -restrict -ansi-alias -fno-alias -fimf-precision=low -fast-transcendentals -no-prec-sqrt -no-prec-div -fp-model fast=2 -fno-protect-parens -rcd -ftz -fma -fimf-domain-exclusion=none -qopt-assume-safe-padding -qopt-report=5 -qopt-report-phase=VEC,PAR,OPENMP,IPO,LOOP -no-diag-message-catalog -DMAX_EXCH_DIST=1 -DUSE_INTRIN256 -DREAL_BYTES=4 -DLAYOUT_3D=Layout_123 -DLAYOUT_4D=Layout_2314 -DTIME_DIM_SIZE=2 -DDEF_RANK_SIZE=1024 -DDEF_BLOCK_SIZE=64 -DDEF_BLOCK_THREADS=2 -DDEF_THREAD_FACTOR=1 -DDEF_PAD=1 -DARCH_HSW -DNO_STORE_INTRINSICS -DUSE_STREAMING_STORE  -fopenmp   -c -o src/stencil_calc.hsw.o src/stencil_calc.cpp
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
src/stencil_calc.cpp(701): error: identifier "MPI_INTEGER8" is undefined
              MPI_Bcast(&coords[rn][0], num_dims, MPI_INTEGER8,
                                                  ^

src/stencil_calc.cpp(701): error: identifier "MPI_Bcast" is undefined
              MPI_Bcast(&coords[rn][0], num_dims, MPI_INTEGER8,
              ^

compilation aborted for src/stencil_calc.cpp (code 2)
make: *** [src/stencil_calc.hsw.o] Error 2

**Comment by chuckyount** [comment]
Oops--sorry about that. I added some MPI features and apparently didn't retest without MPI. I will make a fix. Thanks for the bug report!

**Comment by chuckyount** [comment]
Please try it now and let me know if it's ok.

**Comment by dkokron** [comment]
Chuck,

yup, that works.  Thanks for the quick fix.

Dan
